<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>HTFHelper</AssemblyName>
    <RootNamespace>HTF</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\ref\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\ref\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="FishNet.Runtime">
      <HintPath>..\ref\FishNet.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="FishyUnityTransport">
      <HintPath>..\ref\FishyUnityTransport.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\ref\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\ref\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\ref\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
